# Form implementation generated from reading ui file 'addEquipUIForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from db_operation_functions import queryComposer
from functools import partial


class addTypeUIDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(260, 90)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 235, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 45, 195, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.confirmButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.confirmButton.setObjectName("confirmButton")
        confirm_button = partial(self.confirm_button_slot, Dialog=Dialog)
        self.confirmButton.clicked.connect(confirm_button)
        self.horizontalLayout_2.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.cancelButton.setObjectName("cancelButton")
        self.cancelButton.clicked.connect(lambda: Dialog.close())
        self.horizontalLayout_2.addWidget(self.cancelButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название типа"))
        self.confirmButton.setText(_translate("Dialog", "Добавить"))
        self.cancelButton.setText(_translate("Dialog", "Отмена"))

    def confirm_button_slot(self, Dialog: QtWidgets.QDialog = None):
        qc = queryComposer("equipment_type")
        qc.insert_query({"equipment_type_name": self.lineEdit.text()})
        qc.close_connection()
        Dialog.close()


class addEquipUIDIalog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 530)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 365, 460))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.equipNameLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipNameLabel.setObjectName("equipNameLabel")
        self.gridLayout.addWidget(self.equipNameLabel, 0, 0, 1, 1)
        self.equipNameField = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.equipNameField.setObjectName("equipNameField")
        self.gridLayout.addWidget(self.equipNameField, 0, 1, 1, 1)
        self.equipDesignationLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipDesignationLabel.setObjectName("equipDesignationLabel")
        self.gridLayout.addWidget(self.equipDesignationLabel, 1, 0, 1, 1)
        self.equipDesignationField = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.equipDesignationField.setObjectName("equipDesignationField")
        self.gridLayout.addWidget(self.equipDesignationField, 1, 1, 1, 1)
        self.equipTypeLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipTypeLabel.setObjectName("equipTypeLabel")
        self.gridLayout.addWidget(self.equipTypeLabel, 2, 0, 1, 1)
        self.equipTypeComboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.equipTypeComboBox.setObjectName("equipTypeComboBox")
        self.gridLayout.addWidget(self.equipTypeComboBox, 2, 1, 1, 1)
        self.addTypeToolButton = QtWidgets.QToolButton(parent=self.gridLayoutWidget)
        self.addTypeToolButton.setObjectName("addTypeToolButton")
        self.addTypeToolButton.clicked.connect(self.add_type_button_slot)
        self.gridLayout.addWidget(self.addTypeToolButton, 2, 2, 1, 1)
        self.equipManufactLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipManufactLabel.setObjectName("equipManufactLabel")
        self.gridLayout.addWidget(self.equipManufactLabel, 3, 0, 1, 1)
        self.equipManufactField = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.equipManufactField.setObjectName("equipManufactField")
        self.gridLayout.addWidget(self.equipManufactField, 3, 1, 1, 1)
        self.equipLifetimeLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipLifetimeLabel.setObjectName("equipLifetimeLabel")
        self.gridLayout.addWidget(self.equipLifetimeLabel, 4, 0, 1, 1)
        self.equipLifetimeField = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.equipLifetimeField.setObjectName("equipLifetimeField")
        self.equipLifetimeField.setValidator(QtGui.QDoubleValidator())
        self.gridLayout.addWidget(self.equipLifetimeField, 4, 1, 1, 1)
        self.equipStatusLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipStatusLabel.setObjectName("equipStatusLabel")
        self.gridLayout.addWidget(self.equipStatusLabel, 5, 0, 1, 1)
        self.equipStatusComboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.equipStatusComboBox.setObjectName("equipStatusComboBox")
        self.equipStatusComboBox.addItems(["Не активен", "Активен"])
        self.equipStatusComboBox.currentIndexChanged.connect(self.date_enabler)
        self.gridLayout.addWidget(self.equipStatusComboBox, 5, 1, 1, 1)
        self.equipInstallationDateLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipInstallationDateLabel.setObjectName("equipInstallationDateLabel")
        self.gridLayout.addWidget(self.equipInstallationDateLabel, 6, 0, 1, 1)
        self.equipInstallationDateField = QtWidgets.QDateEdit(
            parent=self.gridLayoutWidget
        )
        self.equipInstallationDateField.setObjectName("equipInstallationDateField")
        self.gridLayout.addWidget(self.equipInstallationDateField, 6, 1, 1, 1)
        self.equipInstallationDateField.setEnabled(False)
        self.equipDetailsLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.equipDetailsLabel.setObjectName("equipDetailsLabel")
        self.equipDetailsLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.gridLayout.addWidget(self.equipDetailsLabel, 7, 0, 1, 1)
        self.equipDetailsField = QtWidgets.QTextEdit(parent=self.gridLayoutWidget)
        self.equipDetailsField.setObjectName("equipDetailsField")
        self.gridLayout.addWidget(self.equipDetailsField, 7, 1, 1, 1)

        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 490, 195, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.confirmButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.confirmButton.setObjectName("confirmButton")
        confirm_button = partial(self.confirm_button_slot, Dialog=Dialog)
        self.confirmButton.clicked.connect(confirm_button)
        self.buttonLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.cancelButton.clicked.connect(lambda: Dialog.close())

        self.equip_type_placeholder()
        # self.manufact_data_placeholder()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление оборудования"))
        self.equipNameLabel.setText(_translate("Dialog", "Название"))
        self.addTypeToolButton.setText(_translate("Dialog", "+"))
        self.equipLifetimeLabel.setText(_translate("Dialog", "Срок работы"))
        self.equipTypeLabel.setText(_translate("Dialog", "Тип оборудования"))
        self.equipDesignationLabel.setText(_translate("Dialog", "Обозначение"))
        self.equipInstallationDateLabel.setText(_translate("Dialog", "Дата установки"))
        self.equipManufactLabel.setText(_translate("Dialog", "Производитель"))
        self.equipDetailsLabel.setText(_translate("Dialog", "Примечание"))
        self.equipStatusLabel.setText(_translate("Dialog", "Статус"))
        # self.equipSensorLabel.setText(_translate("Dialog", "Датчики"))
        # self.changeSensorToolButton.setText(_translate("Dialog", "+"))
        self.confirmButton.setText(_translate("Dialog", "Добавить"))
        self.cancelButton.setText(_translate("Dialog", "Отмена"))

    # data loaders
    def equip_type_data_loader(self):
        qc = queryComposer("equipment_type")
        raw_equip_type_data = qc.select_query(order_opt=["equipment_type_id"])
        qc.close_connection()
        self.equip_type_id_ref = {
            e_type["equipment_type_id"]: e_type["equipment_type_name"]
            for e_type in raw_equip_type_data
        }

    # def manufact_data_loader(self):
    #     qc = queryComposer("equipment_manufacturer")
    #     raw_manufact_data = qc.select_query()
    #     qc.close_connection()
    #     self.manufact_id_ref = {
    #         manufact["equipment_manufacturer_id"]: manufact[
    #             "equipment_manufacturer_name"
    #         ]
    #         for manufact in raw_manufact_data
    #     }

    # data placeholders
    def equip_type_placeholder(self):
        self.equip_type_data_loader()
        self.equipTypeComboBox.clear()
        self.equipTypeComboBox.addItems(list(self.equip_type_id_ref.values()))

    # def manufact_data_placeholder(self):
    #     self.manufact_data_loader()
    #     self.equipManufactField.setCompleter(
    #         QtWidgets.QCompleter(self.manufact_id_ref.values())
    #     )

    def add_type_button_slot(self):
        typeDialog = QtWidgets.QDialog()
        addTypeUIForm = addTypeUIDialog()
        addTypeUIForm.setupUi(typeDialog)
        typeDialog.exec()
        self.equip_type_placeholder()

    def date_enabler(self):
        if self.equipStatusComboBox.currentIndex() == 0:
            self.equipInstallationDateField.setEnabled(False)
        else:
            self.equipInstallationDateField.setEnabled(True)

    def confirm_button_slot(self, Dialog):
        qc = queryComposer("equipment")
        values = {
            "equipment_name": self.equipNameField.text(),
            "equipment_designation": self.equipDesignationField.text(),
            "equipment_details": self.equipDetailsField.toPlainText(),
            "equipment_status": self.equipStatusComboBox.currentIndex() == 1,
            "equipment_average_lifetime": str(self.equipLifetimeField.text()),
            "equipment_manufacturer_name": self.equipManufactField.text(),
            "equipment_type_id": str(
                list(self.equip_type_id_ref.keys())[
                    self.equipTypeComboBox.currentIndex()
                ]
            ),
        }
        if self.equipStatusComboBox.currentIndex() == 1:
            values[
                "equipment_installation_date"
            ] = self.equipInstallationDateField.text()
        qc.insert_query(values)
        qc.close_connection()
        Dialog.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = addEquipUIDIalog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
