# Form implementation generated from reading ui file 'equipSensorManagementForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from db_operation_functions import queryComposer
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(590, 250)
        self.avaliableSensorLabel = QtWidgets.QLabel(parent=Dialog)
        self.avaliableSensorLabel.setGeometry(QtCore.QRect(10, 10, 120, 15))
        self.avaliableSensorLabel.setObjectName("avaliableSensorLabel")
        self.equipSensorLabel = QtWidgets.QLabel(parent=Dialog)
        self.equipSensorLabel.setGeometry(QtCore.QRect(320, 10, 150, 20))
        self.equipSensorLabel.setObjectName("equipSensorLabel")
        self.equipSensorListWidget = QtWidgets.QListWidget(parent=Dialog)
        self.equipSensorListWidget.setGeometry(QtCore.QRect(320, 40, 255, 190))
        self.equipSensorListWidget.setObjectName("equipSensorListWidget")
        item = QtWidgets.QListWidgetItem()
        self.equipSensorListWidget.addItem(item)
        self.avaliableSensorListWidget = QtWidgets.QListWidget(parent=Dialog)
        self.avaliableSensorListWidget.setGeometry(QtCore.QRect(10, 40, 250, 190))
        self.avaliableSensorListWidget.setObjectName("avaliableSensorListWidget")
        self.sensorAddToolButton = QtWidgets.QToolButton(parent=Dialog)
        self.sensorAddToolButton.setGeometry(QtCore.QRect(275, 80, 30, 20))
        self.sensorAddToolButton.setObjectName("sensorAddToolButton")
        self.addToEquipToolButton = QtWidgets.QToolButton(parent=Dialog)
        self.addToEquipToolButton.setGeometry(QtCore.QRect(275, 110, 30, 20))
        self.addToEquipToolButton.setObjectName("addToEquipToolButton")
        self.setFreeToolButton = QtWidgets.QToolButton(parent=Dialog)
        self.setFreeToolButton.setGeometry(QtCore.QRect(275, 140, 30, 20))
        self.setFreeToolButton.setObjectName("setFreeToolButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.avaliableSensorLabel.setText(_translate("Dialog", "Свободные датчики"))
        self.addToEquipToolButton.setText(_translate("Dialog", ">>"))
        self.equipSensorLabel.setText(_translate("Dialog", "Датчики в оборудовании"))
        __sortingEnabled = self.equipSensorListWidget.isSortingEnabled()
        self.equipSensorListWidget.setSortingEnabled(False)
        self.equipSensorListWidget.setSortingEnabled(__sortingEnabled)
        self.setFreeToolButton.setText(_translate("Dialog", "<<"))
        __sortingEnabled = self.avaliableSensorListWidget.isSortingEnabled()
        self.avaliableSensorListWidget.setSortingEnabled(False)
        self.avaliableSensorListWidget.setSortingEnabled(__sortingEnabled)
        self.sensorAddToolButton.setText(_translate("Dialog", "+"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
