# Form implementation generated from reading ui file 'actualPMEdit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from db_operation_functions import queryComposer
from functools import partial


class addMeasureUIDialog(object):
    def setupUi(self, Dialog, risk_id):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 420)
        self.h_layout_widget = QtWidgets.QWidget(parent=Dialog)
        self.h_layout_widget.setGeometry(QtCore.QRect(190, 375, 195, 40))
        self.h_layout_widget.setObjectName("h_layout_widget")
        self.h_button_layout = QtWidgets.QHBoxLayout(self.h_layout_widget)
        self.h_button_layout.setContentsMargins(0, 0, 0, 0)
        self.h_button_layout.setObjectName("h_button_layout")
        self.confirm_button = QtWidgets.QPushButton(parent=self.h_layout_widget)
        self.confirm_button.setObjectName("confirm_button")
        _confirm_button_slot = partial(self.confirm_button_slot, Dialog=Dialog)
        self.confirm_button.clicked.connect(_confirm_button_slot)
        self.h_button_layout.addWidget(self.confirm_button)
        self.cancel_button = QtWidgets.QPushButton(parent=self.h_layout_widget)
        self.cancel_button.setObjectName("cancel_button")
        self.cancel_button.clicked.connect(lambda: Dialog.close())
        self.h_button_layout.addWidget(self.cancel_button)
        self.h_layout_widget_n = QtWidgets.QWidget(parent=Dialog)
        self.h_layout_widget_n.setGeometry(QtCore.QRect(10, 5, 370, 360))
        self.h_layout_widget_n.setObjectName("h_layout_widget_n")
        self.g_layout_widget = QtWidgets.QGridLayout(self.h_layout_widget_n)
        self.g_layout_widget.setContentsMargins(0, 0, 0, 0)
        self.g_layout_widget.setSpacing(20)
        self.g_layout_widget.setObjectName("g_layout_widget")
        self.date_field = QtWidgets.QDateEdit(parent=self.h_layout_widget_n)
        self.date_field.setEnabled(False)
        self.date_field.setObjectName("date_field")
        self.g_layout_widget.addWidget(self.date_field, 3, 2, 1, 1)
        self.risk_name_label = QtWidgets.QLabel(parent=self.h_layout_widget_n)
        self.risk_name_label.setObjectName("risk_name_label")
        self.g_layout_widget.addWidget(self.risk_name_label, 0, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(parent=self.h_layout_widget_n)
        self.status_label.setObjectName("status_label")
        self.g_layout_widget.addWidget(self.status_label, 2, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(parent=self.h_layout_widget_n)
        self.nameLabel.setObjectName("nameLabel")
        self.g_layout_widget.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.details_label = QtWidgets.QLabel(parent=self.h_layout_widget_n)
        self.details_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.details_label.setObjectName("details_label")
        self.g_layout_widget.addWidget(self.details_label, 4, 0, 1, 1)
        self.date_label = QtWidgets.QLabel(parent=self.h_layout_widget_n)
        self.date_label.setObjectName("date_label")
        self.g_layout_widget.addWidget(self.date_label, 3, 0, 1, 1)
        self.status_combobox = QtWidgets.QComboBox(parent=self.h_layout_widget_n)
        self.status_combobox.setObjectName("status_combobox")
        self.status_combobox.addItem("")
        self.status_combobox.addItem("")
        self.status_combobox.currentIndexChanged.connect(self.date_field_enabler)
        self.g_layout_widget.addWidget(self.status_combobox, 2, 2, 1, 1)
        self.risk_combobox = QtWidgets.QComboBox(parent=self.h_layout_widget_n)
        self.risk_combobox.setObjectName("risk_combobox")
        self.g_layout_widget.addWidget(self.risk_combobox, 0, 1, 1, 2)
        self.name_field = QtWidgets.QLineEdit(parent=self.h_layout_widget_n)
        self.name_field.setObjectName("name_field")
        self.g_layout_widget.addWidget(self.name_field, 1, 1, 1, 2)
        self.details_field = QtWidgets.QTextEdit(parent=self.h_layout_widget_n)
        self.details_field.setObjectName("details_field")
        self.g_layout_widget.addWidget(self.details_field, 4, 1, 1, 2)
        self.risk_name_label.setBuddy(self.risk_combobox)
        self.status_label.setBuddy(self.status_combobox)
        self.nameLabel.setBuddy(self.name_field)
        self.details_label.setBuddy(self.details_field)
        # data loader
        self.risk_data_loader()

        # data_placeholder
        self.risk_data_placeholder(risk_id)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.risk_combobox, self.confirm_button)
        Dialog.setTabOrder(self.confirm_button, self.cancel_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление меры"))
        self.confirm_button.setText(_translate("Dialog", "Добавить"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
        self.risk_name_label.setText(_translate("Dialog", "Фактор риска"))
        self.status_label.setText(_translate("Dialog", "Статус"))
        self.nameLabel.setText(_translate("Dialog", "Мера"))
        self.details_label.setText(_translate("Dialog", "Описание"))
        self.date_label.setText(_translate("Dialog", "Дата принятия"))
        self.status_combobox.setItemText(0, _translate("Dialog", "Не принята"))
        self.status_combobox.setItemText(1, _translate("Dialog", "Принята"))

    def risk_data_loader(self):
        qc = queryComposer("risk_register")
        raw_risk_data = qc.select_query(order_opt=["risk_id"])
        qc.close_connection()
        self.risk_data_id_ref = {
            risk["risk_id"]: risk["risk_name"] for risk in raw_risk_data
        }

    def risk_data_placeholder(self, risk_id):
        self.risk_combobox.addItems(self.risk_data_id_ref.values())
        self.risk_combobox.setCurrentIndex(
            list(self.risk_data_id_ref.keys()).index(risk_id)
        )

    def date_field_enabler(self):
        """_summary_"""
        if self.status_combobox.currentIndex() == 0:
            self.date_field.setEnabled(False)
        else:
            self.date_field.setEnabled(True)

    def confirm_button_slot(self, Dialog: QtWidgets.QDialog = None) -> None:
        qc = queryComposer("prevention_measures")
        values = {}
        values["risk_id"] = list(self.risk_data_id_ref.keys())[
            self.risk_combobox.currentIndex()
        ]
        values["prevention_measure_name"] = self.name_field.text()
        values["prevention_measure_details"] = self.details_field.toPlainText()
        values["prevention_measure_status"] = bool(self.status_combobox.currentIndex())
        values["prevention_measure_date"] = (
            self.date_field.text()
            if bool(self.status_combobox.currentIndex())
            else None
        )
        qc.insert_query(values)
        qc.close_connection()
        Dialog.close()


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = addMeasureUIDialog()
    ui.setupUi(Dialog, 1)
    Dialog.show()
    sys.exit(app.exec())
